### ISSUE TITLE
this.constructor._checkRequired is not a function

### ISSUE THREAD

**Issue by joneldiablo** [konsumer/mongoose-type-email#24]
I having get this error: _UserModel validation failed: email: this.constructor._checkRequired is not a function_

this is my schema:

```
const mongoose = require('../db');
require('mongoose-type-email');

const userSchema = new mongoose.Schema({
  name: {
    type: String,
    required: true
  },
  email: {
    type: mongoose.SchemaTypes.Email,
    required: true,
    index: {
      unique: true
    }
  },
  password: {
    type: String,
    required: true
  },
  phoneNumber: String
});

module.exports = mongoose.model('UserModel', userSchema);
```

**Comment by cwoebker** [comment]
We also just encountered this issue. Turns out it still works with all mongoose versions before 5.4.
I guess this library needs to incorporate some new fixes to deal with this update. 

Article about the changes:

http://thecodebarbarian.com/whats-new-in-mongoose-54-global-schematype-configuration.html

**Comment by pwarelis** [comment]
I'm getting the same error

**Comment by samermurad** [comment]
I forked the library and fixed the error
https://github.com/samermurad/mongoose-type-email
I also created a pull request #25

**Comment by konsumer** [comment]
published as mongoose-type-email@1.0.11.

Thanks!
